ci(gitops): mention User's branch name in PR title
ci(gitops): debug why train branch is missing

ci(gitops): use origin/release-train to merge 'boarding' branch into

ci(gitops): use local refs for PR, and include sanity check prior to opening PR

diff --git a/.github/workflows/load-to-rt.yml b/.github/workflows/load-to-rt.yml
--- a/.github/workflows/load-to-rt.yml
+++ b/.github/workflows/load-to-rt.yml
@@ -43,7 +43,7 @@ jobs:
 
           echo USER_BRANCH=$name >> $GITHUB_OUTPUT
 
-      ### Test User Branch before Boarding ###
+      ### Put User Branch on Boarding Branch to Test before merging to Release Train
 
       - run: git checkout ${{ env.MAIN_BRANCH }}
       - run: git checkout -b ${{ env.BOARDING }}
@@ -60,6 +60,7 @@ jobs:
       # Push Boarding and Trigger CI Tests on the 'CI/CD Pipeline'
       - run: git push -u origin HEAD
 
+      ### Release Train - Setup ###
       - run: echo UPSTREAM_TRAIN="$(git ls-remote --heads origin '${{ env.TRAIN }}')" >> $GITHUB_ENV
       - id: remote_train
         run: |
@@ -73,11 +74,23 @@ jobs:
 
       # if Release Train does not exist, create it
       - name: If Upstream Release Train branch does not exist, create it
-        if: ${{ ! steps.remote_train.outputs.TRAIN_EXISTS }}
+        if: ${{ steps.remote_train.outputs.TRAIN_EXISTS  }}
         run: |
           git checkout ${{ env.MAIN_BRANCH }}
           git checkout -b ${{ env.TRAIN }}
           git push -u origin HEAD
+
+      ### Release Train - Check ###
+      - name: "Verify 'release-train' is found in list of local branches"
+        run: |
+          git branch --list
+          git branch --list | grep ${{ env.TRAIN }}
+          if [[ $? -ne 0 ]]; then
+            echo "[ERROR] Failed to setup Release Train !"
+            exit 1
+          fi
+
+      - run: git log --graph --decorate --color --all --stat
 
       ############## PR ##############
       - name: 'Create PR   ${{ env.BOARDING }}  -->  ${{ env.TRAIN }}'
@@ -85,7 +98,7 @@ jobs:
         # --base is the branch you want to merge the changes into
         run: |
           gh pr create --head "${{ env.BOARDING }}" --base "${{ env.TRAIN }}"  \
-            --title "Onboarding Release Train - Merging into ${{ env.TRAIN }} Branch" \
+            --title "Boarding '${{ steps.user_branch.outputs.USER_BRANCH }}' on Release Train - Merging into ${{ env.TRAIN }} Branch" \
             --body "This PR is automatically generated by a GitHub Action workflow. \
             It contains changes that the Developer wants to be included in the next Release. \
             \n\n\
