gitops: select Required Checks at Runtime/Dynamically, by examining changes'

diff --git a/.github/workflows/merge-to-train.yml b/.github/workflows/merge-to-train.yml
--- a/.github/workflows/merge-to-train.yml
+++ b/.github/workflows/merge-to-train.yml
@@ -7,6 +7,11 @@ on:
     types: [closed]
     branches:  # ALLOWED Base Branches
       - boarding-auto
+      ## IMPORTANT: below branches synergize with Protection Rules
+      - test-distro
+      - test-docs
+      - test-distro-docs
+
 # Listens to Event fired: When PR is Closed, and PR targets 'boarding-auto' branch
 # Case GITOPS: Trigger when Auto Merge PR 'User Branch' --> 'boarding-auto'
 jobs:
@@ -29,33 +34,26 @@ jobs:
 
       - name: "Ensure Upstream '${{ env.MAIN_BR }}' is tracked (has local counterpart)"
         run: git branch --track "${{ env.MAIN_BR }}" "origin/${{ env.MAIN_BR }}" || echo "[WARNING] Branch '${{ env.MAIN_BR }}' already exists locally"
-      
+
+      - run: |
+          INCOMING_BR="${{ github.event.pull_request.base.ref }}"
+          echo "INCOMING_BR: $INCOMING_BR"
+          echo INCOMING_BR=$INCOMING_BR >> $GITHUB_ENV
+
+      - name: Track Protected Branch '${{ env.INCOMING_BR }}' with local counterpart
+        run: git branch --track "${{ env.INCOMING_BR }}" "origin/${{ env.INCOMING_BR }}"
+
       - name: "Ensure Upstream '${{ env.BOARDING }}' is tracked (has local counterpart)"
         run: git branch --track "${{ env.BOARDING }}" "origin/${{ env.BOARDING }}" || echo "[WARNING] Branch '${{ env.BOARDING }}' already exists locally"
 
-      # either create a Train branch on top of master unless its Upstream exists (just track it)
-      - run: git branch --track "${{ env.TRAIN }}" "origin/${{ env.TRAIN }}" || true
-
-      - name: "Search for '${{ env.TRAIN }}' in local Branches"
-        run: |
-          LOCAL_TRAIN=$(git branch --list ${{ env.TRAIN }})
-          echo "[DEBUG] LOCAL_TRAIN:"
-          echo "${LOCAL_TRAIN}"
-          echo "LOCAL_TRAIN=${LOCAL_TRAIN}" >> $GITHUB_ENV
-
-      - run: echo "TRAIN_EXISTS=${{ env.LOCAL_TRAIN == '' && 'false' || 'true' }}" >> $GITHUB_ENV
-
-      - if: ${{ env.TRAIN_EXISTS == 'false' }}
-        run: |
-          echo "[INFO] Branch '${{ env.TRAIN }}' does not exist. Creating it .."
-          git checkout -b ${{ env.TRAIN }} ${{ env.MAIN_BR }}
-          git push origin ${{ env.TRAIN }}
+      # create a Train branch on top of master unless its Upstream exists (just track it)
+      - run: git branch --track "${{ env.TRAIN }}" "origin/${{ env.TRAIN }}" || (git checkout -b ${{ env.TRAIN }} ${{ env.MAIN_BR }} && git push origin ${{ env.TRAIN }})
 
       ############## PR ##############
-      - name: Sanity Check that '${{ env.BOARDING }}' and '${{ env.TRAIN }}' branches exist
+      - name: Sanity Check that '${{ env.INCOMING_BR }}' and '${{ env.TRAIN }}' branches exist
         run: |
-          if [ -z "$(git branch --list ${BOARDING})" ]; then
-            echo "[ERROR] Branch '${BOARDING}' does not exist. Exiting .."
+          if [ -z "$(git branch --list ${INCOMING_BR})" ]; then
+            echo "[ERROR] Branch '${INCOMING_BR}' does not exist. Exiting .."
             exit 1
           fi
           if [ -z "$(git branch --list ${TRAIN})" ]; then
@@ -63,12 +61,12 @@ jobs:
             exit 1
           fi
 
-      - name: "Create PR  Head: '${{ env.BOARDING }}''  -->  Base: '${{ env.TRAIN }}'"
+      - name: "Create PR  Head: '${{ env.INCOMING_BR }}''  -->  Base: '${{ env.TRAIN }}'"
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          gh pr create --head "${{ env.BOARDING }}" --base "${{ env.TRAIN }}" \
-            --title "Merging '${{ env.BOARDING }}', carrying '${{ steps.user_branch.outputs.USER_BRANCH }}', into '${{ env.TRAIN }}'" \
+          gh pr create --head "${{ env.INCOMING_BR }}" --base "${{ env.TRAIN }}" \
+            --title "Merging '${{ env.INCOMING_BR }}', carrying '${{ steps.user_branch.outputs.USER_BRANCH }}', into '${{ env.TRAIN }}'" \
             --body "## :train: Boarding onto the Release Train :train:
 
           This PR is automatically generated by a GitHub Action workflow. It's part of the process of boarding changes onto the **Release Train** branch, setting the stage for the next steps in our GitOps journey.
@@ -95,8 +93,8 @@ jobs:
           "
 
       ############## Merge ##############
-      - name: 'Merge PR   ${{ env.BOARDING }}  -->  ${{ env.TRAIN }}'
-        run: gh pr merge "${{ env.BOARDING }}" --auto --merge
+      - name: 'Merge PR   ${{ env.INCOMING_BR }}  -->  ${{ env.TRAIN }}'
+        run: gh pr merge "${{ env.INCOMING_BR }}" --auto --merge --delete-branch
         # --delete-branch --squash
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
