ci(bandit): ass Job for Bandit Scan and Continuous Security Reporting

diff --git a/.github/workflows/policy_lint.yml b/.github/workflows/policy_lint.yml
--- a/.github/workflows/policy_lint.yml
+++ b/.github/workflows/policy_lint.yml
@@ -144,6 +144,91 @@ jobs:
         if: ${{ matrix.platform != 'windows-latest' }}
         run: tox -e prospector -vv -s false
 
+  bandit:
+    name: "Bandit: Security Analysis"
+    runs-on: ubuntu-latest
+    needs: decide_run_lint
+    if: always() && needs.decide_run_lint.outputs.RUN_SQA == 'true'
+    env:
+      _SARIF_FILE: results-sarif.json
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python ${{ inputs.python_version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ inputs.python_version }}
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install tox==3.28
+
+      ## Run BANDIT to identify CWEs ##
+      - name: 'Bandit: Security Analysis'
+        run: tox -e bandit -vv -s false -- -q -f sarif -o "${{ env._SARIF_FILE }}"
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@main
+        with:
+          name: ${{ env._SARIF_FILE }}
+          path: ${{ env._SARIF_FILE }}
+          if-no-files-found: error
+
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: ${{ env._SARIF_FILE }}
+
+      - name: 'Parse Bandit Results, and prepare comparing LOW, MEDIUM, and HIGH'
+        id: parse_bandit_results
+        run: |
+          # Parse Totals Object
+          TOTALS=$(jq '.runs[0].properties.metrics._totals' results-sarif.json)
+
+          # Find CWE's of HIGH Severity
+          HIGH=$(echo $TOTALS | jq '.["SEVERITY.HIGH"]')
+
+          # Find CWE's of MEDIUM Severity
+          MEDIUM=$(echo $TOTALS | jq '.["SEVERITY.MEDIUM"]')
+
+          # Find CWE's of LOW Severity
+          LOW=$(echo $TOTALS | jq '.["SEVERITY.LOW"]')
+
+          # Report and Env
+          echo HIGH=$HIGH >> $GITHUB_ENV
+          echo MEDIUM=$MEDIUM >> $GITHUB_ENV
+          echo LOW=$LOW >> $GITHUB_ENV
+
+      - name: Write to Job Step Summary
+        run: |
+          echo "## Bandit - Results" >> $GITUB_STEP_SUMMARY
+          echo "HIGH: $HIGH" >> $GITUB_STEP_SUMMARY
+          echo "MEDIUM: $MEDIUM" >> $GITUB_STEP_SUMMARY
+          echo "LOW: $LOW" >> $GITUB_STEP_SUMMARY
+
+      #### JOB STATUS ####
+      - name: "If we found more than ${{ fromJson(inputs.bandit).h }} HIGH Severity CWE's, Fail!"
+        if: ${{ fromJson(inputs.bandit).h < steps.parse_bandit_results.outputs.HIGH }}
+        run: |
+          echo "Bandit Failed! | Found more HIGH Severity CWE's in code than allowed/acceptable amount."
+          echo "[ERROR] **HIGH**: ${{ steps.parse_bandit_results.outputs.HIGH }} > ${{ fromJson(inputs.bandit).h }}" >> $GITUB_STEP_SUMMARY
+          exit 1
+
+      - name: "If we found more than ${{ fromJson(inputs.bandit).m }} MEDIUM Severity CWE's, Fail!"
+        if: ${{ fromJson(inputs.bandit).m < steps.parse_bandit_results.outputs.MEDIUM }}
+        run: |
+          echo "Bandit Failed! | Found more MEDIUM Severity CWE's in code than allowed/acceptable amount."
+          echo "[ERROR] **MEDIUM**: ${{ steps.parse_bandit_results.outputs.MEDIUM }} > ${{ fromJson(inputs.bandit).m }}" >> $GITUB_STEP_SUMMARY
+          exit 1
+
+      - name: "If we found more than ${{ fromJson(inputs.bandit).l }} LOW Severity CWE's, Fail!"
+        if: ${{ fromJson(inputs.bandit).l < steps.parse_bandit_results.outputs.LOW }}
+        run: |
+          echo "Bandit Failed! | Found more LOW Severity CWE's in code than allowed/acceptable amount."
+          echo "[ERROR] **LOW**: ${{ steps.parse_bandit_results.outputs.LOW }} > ${{ fromJson(inputs.bandit).l }}" >> $GITUB_STEP_SUMMARY
+          exit 1
+
+      - run: echo "**Bandit Passed!**" >> $GITUB_STEP_SUMMARY
+
   legacy_pylint:
     runs-on: ubuntu-latest
     needs: lint_policy
