ci(lint): dedicate a Job Matrix for running Lint Checks
test Lint Job Matrix

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -40,7 +40,8 @@ env:
   FULL_MATRIX_STRATEGY: "{\"platform\": [\"ubuntu-latest\", \"macos-latest\", \"windows-latest\"], \"python-version\": [\"3.9\", \"3.10\"]}"
   UBUNTU_PY310_STRATEGY: "{\"platform\":[\"ubuntu-latest\"], \"python-version\":[\"3.10\"]}"
   TEST_STRATEGY: "{\"platform\":[\"ubuntu-latest\"], \"python-version\":[\"3.10\", \"3.9\"]}"
-  RUN_UNIT_TESTS: "true"
+  RUN_UNIT_TESTS: "false"
+  RUN_LINT_CHECKS: "true"
   BUILD_DOCKER: "true"
   DRAW_DEPENDENCIES: "true"
 
@@ -56,6 +57,7 @@ jobs:
       TESTS_ENABLED: ${{ steps.pass-env-to-output.outputs.TESTS_ENABLED }}
       DOCKER_ENABLED: ${{ steps.pass-env-to-output.outputs.DOCKER_ENABLED }}
       DRAW_DEPS_SVG_GRAPHS: ${{ steps.pass-env-to-output.outputs.DRAW_DEPS_SVG_GRAPHS }}
+      RUN_LINT: ${{ steps.pass-env-to-output.outputs.RUN_LINT }}
     steps:
       - name: Pass 'env' section variables to GITHUB_OUTPUT
         id: pass-env-to-output
@@ -66,11 +68,49 @@ jobs:
           if [[ $BRANCH_NAME == "master" || $BRANCH_NAME == "main" || $BRANCH_NAME == "stress-test" || $GITHUB_REF == refs/tags/* ]]; then
             echo "matrix=$FULL_MATRIX_STRATEGY" >> $GITHUB_OUTPUT
           else
-            echo "matrix=$UBUNTU_PY310_STRATEGY" >> $GITHUB_OUTPUT
+            echo "matrix=$TEST_STRATEGY" >> $GITHUB_OUTPUT
           fi
           echo "TESTS_ENABLED=$RUN_UNIT_TESTS" >> $GITHUB_OUTPUT
           echo "DOCKER_ENABLED=$BUILD_DOCKER" >> $GITHUB_OUTPUT
           echo "DRAW_DEPS_SVG_GRAPHS=$DRAW_DEPENDENCIES" >> $GITHUB_OUTPUT
+          echo "RUN_LINT=$RUN_LINT_CHECKS" >> $GITHUB_OUTPUT
+
+  lint:
+    runs-on: ${{ matrix.platform }}
+    needs: set_github_outputs
+    if: ${{ needs.set_github_outputs.outputs.RUN_LINT == 'true' }}
+    strategy:
+      matrix: ${{fromJson(needs.set_github_outputs.outputs.matrix)}}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install tox==3.28 tox-gh-actions
+      - name: Lint check code with Isort and Black
+        if: ${{ matrix.platform != 'windows-latest' }}
+        run: tox -e lint -vv -s false
+      - name: "Check Pylint Score > 8.2/10"
+        if: ${{ matrix.platform != 'windows-latest' }}
+        env:
+          PYLINT_THRESHOLD: 8.2
+        run: |
+          tox -e pylint -vv -s false | tee pylint-result.txt
+          SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
+          # threshold check
+          if awk "BEGIN {exit !($SCORE >= $PYLINT_THRESHOLD)}"; then
+            echo "PyLint Passed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
+          else
+            echo "PyLint Failed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
+            exit 1
+          fi
+      - name: Run tox -e prospector
+        if: ${{ matrix.platform != 'windows-latest' }}
+        run: tox -e prospector -vv -s false
 
   test_suite:
     runs-on: ${{ matrix.platform }}
@@ -92,43 +132,18 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install tox==3.28 tox-gh-actions
 
-    - name: Lint check code with Isort and Black
-      if: ${{ matrix.platform != 'windows-latest' }}
-      run: tox -e lint -vv -s false
-
-    - name: Lint check code with Pylint
-      if: ${{ matrix.platform != 'windows-latest' }}
-      env:
-        PYLINT_THRESHOLD: 8.2
-      run: |
-        tox -e pylint -vv -s false | tee pylint-result.txt
-        SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
-        # threshold check
-        if awk "BEGIN {exit !($SCORE >= $PYLINT_THRESHOLD)}"; then
-          echo "PyLint Passed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-        else
-          echo "PyLint Failed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-          exit 1
-        fi
-
-    - name: Run tox -e prospector
-      if: ${{ matrix.platform != 'windows-latest' }}
-      run: tox -e prospector -vv -s false
-
     - name: Do Type Checking
       run: tox -e type -vv -s false
-
     - name: Parse package version from __init__.py to assist building
-      shell: bash
       id: parse_version
       run: |
         PARSER="src/cookiecutter_python/{{ cookiecutter.project_slug }}/scripts/parse_version.py"
         PARSED_VERSION=$(python "${PARSER}")
         # transform version (ie 1.7.4-rc.1) to match the name of the wheel produced (ie 1.7.4rc1)
+        # TODO modify to also parse 1.7.4-rc
         WHEEL_VERSION=$(echo $PARSED_VERSION | sed -E 's/([^.]*)\.([^.]*)\.([^-]*)-(rc)\.(.*)/\1.\2.\3\4\5/')
         echo "PKG_VERSION=$WHEEL_VERSION" >> $GITHUB_ENV  # to be used in the next step
         echo "SEMVER_PIP_FORMAT=$WHEEL_VERSION" >> $GITHUB_OUTPUT  # to be used in other jobs
-
     - name: Run Unit Tests
       run: tox -vv -s false
       env:
