ci: dynamic 'environment' set by checking if tag on master or release branch
deactivate full matrix for testing purposes

clean code

fix ci

try to properly download wheel artifacts

fix download artifacts

bump version to 1.7.5-rc.11

try to fix

fix

fix

get wheels and sdist and upload to a pypi server

debug

activate sdist built and test

debug

fix ci

debug

debug 1

try to fix

fix

fix

try to fix env vars reading for pypi publish

try to fix

put secrets in workflow variables

deactivate CI Workflow on push for testing purposes

poc: reading variables from Githbu Environment

try to fix

make test valid

fix experiment

rename secret to secrets

remove pypi upload-related workflow variables

update version to 1.7.5-rc.24

try to debug

fix

fix

fix 1

debug

fix

debug 2

fix test scenario

fix

try dynamic Environment

clean code

bump release candidate version number

build: fix Dockerfile syntax

bump release candidate to rc.34

fix Dockerfile

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,11 +1,21 @@
-name: Continuous Integration / Continuous Delivery
-# Stress Test and Build Docker Image
+name: CI/CD Pipeline
+# Continuous Integration / Continuous Delivery
+# CI/CD Pipeline
 
+# Triggers on all branches and tags starting with v
+
+# Full Job Matrix for Stress Testing is activated on 'master', 'dev' and tags
+## We Test factoring Platforms and Python versions
+
+# For other branches only one Job is spawned for Running (Unit) Tests
+
+# Covers Case 1
 # dev has feature/bug-branch and writes code
 # dev wants on each push, 'small' Matrix Tests to trigger
 # all feature/bug branches "have" to merge to 'dev' branch
 # 'dev' branch automatically triggers 'full' Matrix Tests
 
+# Covers Case 2
 # it is time to make a new release
 # 'dev' branch merges into 'release' branch
 # a couple of commits (ie version bump, changelog update) are pushed to 'release'
@@ -17,12 +27,6 @@ name: Continuous Integration / Continuous Delivery
 
 # if all OK then PR merges
 # then a new tag (release) is pushed to github
-
-
-# full Matrix Stress Test on
-#   - push to master/main
-#   - push to stress-test branch
-# we want small Matrix Test on each pushed commit
 
 on:
   push:
@@ -37,7 +41,8 @@ env:
   UBUNTU_PY310_STRATEGY: "{\"platform\":[\"ubuntu-latest\"], \"python-version\":[\"3.10\"]}"
   TEST_STRATEGY: "{\"platform\":[\"ubuntu-latest\"], \"python-version\":[\"3.10\", \"3.9\"]}"
   RUN_UNIT_TESTS: "true"
-  BUILD_DOCKER: "false"
+  BUILD_DOCKER: "true"
+  DRAW_DEPENDENCIES: "true"
 
 jobs:
   # we use the below to read the workflow env vars and be able to use in "- if:" Job conditionals
@@ -50,6 +55,7 @@ jobs:
       matrix: ${{ steps.pass-env-to-output.outputs.matrix }}
       TESTS_ENABLED: ${{ steps.pass-env-to-output.outputs.TESTS_ENABLED }}
       DOCKER_ENABLED: ${{ steps.pass-env-to-output.outputs.DOCKER_ENABLED }}
+      DRAW_DEPS_SVG_GRAPHS: ${{ steps.pass-env-to-output.outputs.DRAW_DEPS_SVG_GRAPHS }}
     steps:
       - name: Pass 'env' section variables to GITHUB_OUTPUT
         id: pass-env-to-output
@@ -58,12 +64,13 @@ jobs:
           BRANCH_NAME=${GITHUB_REF_NAME}
           # BRANCH_NAME=${GITHUB_REF##*/}
           if [[ $BRANCH_NAME == "master" || $BRANCH_NAME == "main" || $BRANCH_NAME == "stress-test" || $GITHUB_REF == refs/tags/* ]]; then
-            echo "matrix=$FULL_MATRIX_STRATEGY" >> $GITHUB_OUTPUT
+            echo "matrix=$TEST_STRATEGY" >> $GITHUB_OUTPUT
           else
             echo "matrix=$UBUNTU_PY310_STRATEGY" >> $GITHUB_OUTPUT
           fi
           echo "TESTS_ENABLED=$RUN_UNIT_TESTS" >> $GITHUB_OUTPUT
           echo "DOCKER_ENABLED=$BUILD_DOCKER" >> $GITHUB_OUTPUT
+          echo "DRAW_DEPS_SVG_GRAPHS=$DRAW_DEPENDENCIES" >> $GITHUB_OUTPUT
 
   test_suite:
     runs-on: ${{ matrix.platform }}
@@ -72,74 +79,78 @@ jobs:
     strategy:
       # This needs to match the first job's name and output parameter
       matrix: ${{fromJSON(needs.set_github_outputs.outputs.matrix)}}
-
+    outputs:
+      SEMVER_PIP_FORMAT: ${{ steps.parse_version.outputs.SEMVER_PIP_FORMAT }}
     steps:
     - uses: actions/checkout@v3
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
-
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         python -m pip install tox==3.28 tox-gh-actions
 
-    # - name: Lint check code with Isort and Black
-    #   if: ${{ matrix.platform != 'windows-latest' }}
-    #   run: tox -e lint -vv -s false
+    - name: Lint check code with Isort and Black
+      if: ${{ matrix.platform != 'windows-latest' }}
+      run: tox -e lint -vv -s false
 
-    # - name: Lint check code with Pylint
-    #   if: ${{ matrix.platform != 'windows-latest' }}
-    #   env:
-    #     PYLINT_THRESHOLD: 8.2
-    #   run: |
-    #     tox -e pylint -vv -s false | tee pylint-result.txt
-    #     SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
-    #     # threshold check
-    #     if awk "BEGIN {exit !($SCORE >= $PYLINT_THRESHOLD)}"; then
-    #       echo "PyLint Passed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-    #     else
-    #       echo "PyLint Failed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
-    #       exit 1
-    #     fi
+    - name: Lint check code with Pylint
+      if: ${{ matrix.platform != 'windows-latest' }}
+      env:
+        PYLINT_THRESHOLD: 8.2
+      run: |
+        tox -e pylint -vv -s false | tee pylint-result.txt
+        SCORE=`sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint-result.txt`
+        # threshold check
+        if awk "BEGIN {exit !($SCORE >= $PYLINT_THRESHOLD)}"; then
+          echo "PyLint Passed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
+        else
+          echo "PyLint Failed | Score: ${SCORE} | Threshold: ${PYLINT_THRESHOLD}"
+          exit 1
+        fi
 
-    # - name: Run tox -e prospector
-    #   if: ${{ matrix.platform != 'windows-latest' }}
-    #   run: tox -e prospector -vv -s false
+    - name: Run tox -e prospector
+      if: ${{ matrix.platform != 'windows-latest' }}
+      run: tox -e prospector -vv -s false
 
-    # - name: Do Type Checking
-    #   run: tox -e type -vv -s false
+    - name: Do Type Checking
+      run: tox -e type -vv -s false
 
     - name: Parse package version from __init__.py to assist building
       shell: bash
+      id: parse_version
       run: |
         PARSER="src/cookiecutter_python/{{ cookiecutter.project_slug }}/scripts/parse_version.py"
         PARSED_VERSION=$(python "${PARSER}")
-        echo "PKG_VERSION=$PARSED_VERSION" >> $GITHUB_ENV
+        # transform version (ie 1.7.4-rc.1) to match the name of the wheel produced (ie 1.7.4rc1)
+        WHEEL_VERSION=$(echo $PARSED_VERSION | sed -E 's/([^.]*)\.([^.]*)\.([^-]*)-(rc)\.(.*)/\1.\2.\3\4\5/')
+        echo "PKG_VERSION=$WHEEL_VERSION" >> $GITHUB_ENV  # to be used in the next step
+        echo "SEMVER_PIP_FORMAT=$WHEEL_VERSION" >> $GITHUB_OUTPUT  # to be used in other jobs
 
     - name: Run Unit Tests
       run: tox -vv -s false
       env:
         PLATFORM: ${{ matrix.platform }}
 
-    # - name: Aggregate Test Coverage Data
-    #   run: tox -e coverage --sitepackages -vv -s false
+    - name: Aggregate Test Coverage Data
+      run: tox -e coverage --sitepackages -vv -s false
 
-    # - run: pip install coverage[toml]>=5.1
-    #   if: ${{ always() }}
+    - run: pip install coverage[toml]>=5.1
+      if: ${{ always() }}
 
-    # - name: Send Coverage Data to Codecov
-    #   uses: codecov/codecov-action@v2
-    #   with:
-    #     directory: ./.tox
-    #     env_vars: OS,PYTHON
-    #     fail_ci_if_error: true
-    #     files: ./.tox/coverage.xml
-    #     flags: unittests
-    #     name: codecov-umbrella
-    #     verbose: true
-    #   if: ${{ always() }}
+    - name: Send Coverage Data to Codecov
+      uses: codecov/codecov-action@v2
+      with:
+        directory: ./.tox
+        env_vars: OS,PYTHON
+        fail_ci_if_error: true
+        files: ./.tox/coverage.xml
+        flags: unittests
+        name: codecov-umbrella
+        verbose: true
+      if: ${{ always() }}
 
     - name: Check for compliance with Python Best Practices
       shell: bash
@@ -147,17 +158,17 @@ jobs:
         DIST_DIR=dist
         echo "DIST_DIR=dist" >> $GITHUB_ENV
         mkdir ${DIST_DIR}
-        # mv ".tox/${DIST_DIR}/cookiecutter_python-${PKG_VERSION}.tar.gz" "${DIST_DIR}"
+        mv ".tox/${DIST_DIR}/cookiecutter_python-${PKG_VERSION}.tar.gz" "${DIST_DIR}"
         mv ".tox/${DIST_DIR}/cookiecutter_python-${PKG_VERSION}-py3-none-any.whl" "${DIST_DIR}"
         # tox -e check -vv -s false
 
-    # - name: Install documentation test dependencies
-    #   if: ${{ matrix.platform == 'macos-latest' && matrix.python-version != '3.6' }}
-    #   run: brew install enchant
+    - name: Install documentation test dependencies
+      if: ${{ matrix.platform == 'macos-latest' && matrix.python-version != '3.6' }}
+      run: brew install enchant
 
-    # - name: Run Documentation Tests
-    #   if: ${{ matrix.platform == 'ubuntu-latest' || matrix.python-version  != '3.6' }}
-    #   run: tox -e docs --sitepackages -vv -s false
+    - name: Run Documentation Tests
+      if: ${{ matrix.platform == 'ubuntu-latest' || matrix.python-version  != '3.6' }}
+      run: tox -e docs --sitepackages -vv -s false
 
     - name: Upload Source & Wheel distributions as Artefacts
       uses: actions/upload-artifact@v2
@@ -165,24 +176,20 @@ jobs:
         name: dist-${{ matrix.platform }}-${{ matrix.python-version }}
         path: ${{ env.DIST_DIR }}
         if-no-files-found: error
-      # path: ${{ env.DIST_DIR }}/cookiecutter_python-${PKG_VERSION}-*.whl
 
-    # - name: Upload Coverage Data as Artefacts
-    #   uses: actions/upload-artifact@v2
-    #   with:
-    #     name: coverage-xml-data
-    #     path: ./.tox/coverage.xml
-    #     if-no-files-found: error
-
-    # - name: Download Coverage Data
-    #   uses: actions/download-artifact@v2
-    #   with:
-    #     name: coverage-xml-data
+    - name: Upload Coverage Data as Artefacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: coverage-xml-data
+        path: ./.tox/coverage.xml
+        if-no-files-found: error
 
 # DRAW PYTHON DEPENDENCY GRAPHS
   check_if_source_code_changed:
     runs-on: ubuntu-latest
     name: Draw Python Dependency Graphs ?
+    needs: set_github_outputs
+    if: needs.set_github_outputs.outputs.DRAW_DEPS_SVG_GRAPHS == 'true'
     outputs:
       SHOULD_DRAW_GRAPHS: ${{ steps.decide_if_should_draw_graphs.outputs.SHOULD_DRAW_GRAPHS }}
     steps:
@@ -224,20 +231,16 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
-
     - name: Install tox
       run: |
         python -m pip install --upgrade pip
         python -m pip install tox==3.28
-
     - name: Install dependencies (ie dot binary of graphviz)
       run: |
         sudo apt-get update -y --allow-releaseinfo-change
         sudo apt-get install -y graphviz
-
     - name: Draw Dependency Graphs as .svg files
       run: tox -e pydeps -vv -s false
-
     - name: Upload Dependency Graphs as artifacts
       uses: actions/upload-artifact@v3
       with:
@@ -260,7 +263,6 @@ jobs:
         IMAGE_TAG="${GITHUB_REF_NAME}"  # this is branch name or tag name
         echo "IMAGE_REF=generate-python:${IMAGE_TAG}" >> $GITHUB_ENV
         docker build -t "${DOCKER_USER}/generate-python:${GITHUB_REF_NAME}" .
-
     - name: Publish Docker Image to DockerHub
       env:
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
@@ -271,62 +273,109 @@ jobs:
         echo "Published in Dockerhub :)"
 
 # PYPI
-# we publish only on tags starting with "v"
-  pypi_environment:
+# we consider publishing on tags starting with "v"
+  on-main-or-release-branch-check:
     runs-on: ubuntu-latest
+    if: startsWith(github.event.ref, 'refs/tags/v')
     outputs:
-      my_env: ${{ steps.setenv.outputs.my_env }}
+      ENVIRONMENT_NAME: ${{ steps.set_environment_name.outputs.ENVIRONMENT_NAME }}
+      AUTOMATED_DEPLOY: ${{ steps.set_environment_name.outputs.AUTOMATED_DEPLOY }}
     steps:
-    - id: setenv
-      run: echo "my_env=TEST_DEPLOYMENT" >> $GITHUB_OUTPUT
-
-  use_outputs_environemnt:
-    needs: pypi_environment
-    runs-on: ubuntu-latest
-    environment:
-      name: ${{ needs.pypi_environment.outputs.my_env }}
-    steps:
-    - name: Testing job environment
-      run: |
-        echo "Hello From ${{ needs.pypi_environment.outputs.my_env }} Envrionment."
-        # That is how you access Environment variables (set in github Environments UI)
-        echo "DEL_ME 2 var is: ${{ vars.DEL_ME }}"
-        # check if TWINE_USERNAME secret is set
-        echo "TWINE_USERNAME is: ${{ secrets.TWINE_USERNAME }}"
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: rickstaa/action-contains-tag@v1
+        id: main_contains_tag
+        with:
+          reference: "master"
+          tag: "${{ github.ref }}"
+      - run: echo "ON_MAIN_BRANCH=${{ steps.main_contains_tag.outputs.retval }}" >> $GITHUB_OUTPUT
+      - uses: rickstaa/action-contains-tag@v1
+        id: release_contains_tag
+        with:
+          reference: "release"
+          tag: "${{ github.ref }}"
+      - run: echo "ON_RELEASE_BRANCH=${{ steps.release_contains_tag.outputs.retval }}" >> $GITHUB_OUTPUT
+      - name: Pick Production or Test Environment, if tag on master or release branch respectively
+        id: set_environment_name
+        run: |
+          DEPLOY=true
+          if [[ "${{ steps.main_contains_tag.outputs.retval }}" == "true" ]]; then
+            echo "ENVIRONMENT_NAME=PROD_DEPLOYMENT" >> $GITHUB_OUTPUT
+          elif [[ "${{ steps.release_contains_tag.outputs.retval }}" == "true" ]]; then
+            echo "ENVIRONMENT_NAME=TEST_DEPLOYMENT" >> $GITHUB_OUTPUT
+          else
+            echo "A tag was pushed but not on master or release branch. No deployment will be done."
+            DEPLOY=false
+          fi
+          echo "AUTOMATED_DEPLOY=$DEPLOY" >> $GITHUB_OUTPUT
 
   pypi_publish:
-    needs: [use_outputs_environemnt, test_suite]
+    needs: [test_suite, on-main-or-release-branch-check]
     runs-on: ubuntu-latest
-    environment:
-      name: ${{ needs.pypi_environment.outputs.my_env }}
     # if we are on tag starting with "v" and if we are on master or dev branch
-    if: startsWith(github.event.ref, 'refs/tags/v') && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release')
+    if: startsWith(github.event.ref, 'refs/tags/v') && ${{ needs.on-main-or-release-branch-check.outputs.AUTOMATED_DEPLOY == 'true' }}
+    environment:
+      name: ${{ needs.on-main-or-release-branch-check.outputs.ENVIRONMENT_NAME }}
+      # name: TEST_DEPLOYMENT
+    env:
+      DIST_DIR: dist
+      PACKAGE_DIST_VERSION: ${{ needs.test_suite.outputs.SEMVER_PIP_FORMAT }}
+            # env:
+      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
+      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
+      PYPI_SERVER: ${{ vars.PYPI_SERVER }}
     steps:
     - uses: actions/checkout@v3
     - name: Download Source & Wheel distributions
       uses: actions/download-artifact@v3
       with:
-        name: dist-${{ matrix.platform }}-${{ matrix.python-version }}
-        path: dist
-    - run: ls -l dist
-    - name: Publish to PyPI
-      env:
-        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
-        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
-        PYPI_SERVER: ${{ vars.PYPI_SERVER }}
+        path: downloaded-artifacts
+    - run: ls -lR downloaded-artifacts
+    - name: Get Publishable files from the Artifacts
       run: |
         TAG="${GITHUB_REF_NAME}"
         SEM_VER="${TAG:1}"  # remove the first character (v)
-
         PARSER="src/cookiecutter_python/{{ cookiecutter.project_slug }}/scripts/parse_version.py"
         PARSED_VERSION=$(python "${PARSER}")
-
         if [[ "${PARSED_VERSION}" != "${SEM_VER}" ]]; then
           echo "ERROR: Version in __init__.py (${PARSED_VERSION}) does not match tag (${SEM_VER})"
           exit 1
         fi
-
-        echo "Publishing $VERSION_TAG to $PYPI_SERVER PyPI"
-
-        # PACKAGE_DIST_VERSION="$SEM_VER" tox -vv -s false -e deploy -- upload --non-interactive --skip-existing
-        echo "Published in PyPI :)"
+    - run: mkdir ${DIST_DIR}
+    - run: |
+        # Get Source Distribution (tar.gz of source code)
+        source_distributions=$(find downloaded-artifacts -type f -name cookiecutter_python*.tar.gz)
+        echo ====== 1 $source_distributions
+        source_distributions_array=($source_distributions)
+        echo ====== 2 $source_distributions
+        source_distribution=${source_distributions_array[0]}  # a *.tar.gz file path
+        echo ======  $source_distribution
+        # Extract the base name (without the path)
+        source_distribution_name=$(basename "$source_distribution")
+        # Check if all source distribution (.tar.gz) files have the same name
+        for file in "${source_distributions_array[@]}"; do
+          if [ "$source_distribution_name" != "$(basename "$file")" ]; then
+            echo "Error: Not all Source Distribution .tar.gz files have the same name!"
+            exit 1
+          fi
+        done
+        echo "source_distribution=$source_distribution" >> $GITHUB_ENV
+      # Copy the source distribution to the dist folder
+    - run: |
+        echo "debug 1: $source_distribution"  # if fail use ${{ env.source_distribution }}
+        echo "debug 2: ${DIST_DIR}"
+        cp "$source_distribution" ${DIST_DIR}
+    - run: |
+        # Get all built Wheels and copy to dist folder
+        for f in `find downloaded-artifacts -type f -name cookiecutter_python*.whl`; do
+          echo "F: $f";
+          # TODO check for duplicates, which means that our build matrix produces the same wheel (need a different compiler that python such as pypy, cython, etc)
+          cp $f ${DIST_DIR}
+        done
+    - name: Install Dependencies
+      run: pip install tox==3.28
+    - run: echo "Publishing $PACKAGE_DIST_VERSION to $PYPI_SERVER PyPI"
+    - name: Publish to PyPI
+      run: tox -vv -s false -e deploy -- upload --non-interactive --skip-existing
+    - run: echo "Published :\)"
