ci: run docs tests after all other tests
enable full ci test workflow

fix ci

flag job as if needed to install pyenchant

fix

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -21,23 +21,38 @@ jobs:
     runs-on: ${{ matrix.platform }}
     strategy:
       matrix:
-        platform: [ubuntu-latest]
-        # platform: [ubuntu-latest, macos-latest]
-        python-version: ["3.8"]
-        # python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
+        # platform: [ubuntu-latest]
+        platform: [ubuntu-latest, macos-latest]
+        # python-version: ["3.8"]
+        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
+        include:
+          - pyenchant: "1"
+            platform: macos-latest
     steps:
     - uses: actions/checkout@v3
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
+    - if: ${{ matrix.pyenchant }}
       run: |
-        python -m pip install --upgrade pip
-        python -m pip install tox tox-gh-actions
+        echo "Need to install Pyenchant :)"
+        brew install pyenchant
+        tox -e docs -vv -s false
 
     # - name: Run Documentation Tests
-    #   run: tox -e docs -vv -s false
+    #   run: |
+    #     if [[ ${{ matrix.pyenchant }} ]]
+    #       then
+    #         echo "Need to install Pyenchant :)"
+    #         brew install pyenchant
+    #       fi
+    #     tox -e docs -vv -s false
+
+    # - name: Install dependencies
+    #   run: |
+    #     python -m pip install --upgrade pip
+    #     python -m pip install tox tox-gh-actions
 
     # - name: Do Lint Checking
     #   run: |
@@ -47,56 +62,68 @@ jobs:
     # - name: Do Type Checking
     #   run: tox -e type -vv -s false
 
-    - name: Specify current package version to assist build tool
-      run: |
-        PARSER="src/cookiecutter_python/{{ cookiecutter.project_slug }}/scripts/parse_version.py"
-        PARSED_VERSION=$(python "${PARSER}")
-        echo $PARSED_VERSION
-        echo "PKG_VERSION=$PARSED_VERSION" >> $GITHUB_ENV
+    # - name: Specify current package version to assist build tool
+    #   run: |
+    #     PARSER="src/cookiecutter_python/{{ cookiecutter.project_slug }}/scripts/parse_version.py"
+    #     PARSED_VERSION=$(python "${PARSER}")
+    #     echo $PARSED_VERSION
+    #     echo "PKG_VERSION=$PARSED_VERSION" >> $GITHUB_ENV
 
-    - name: Run Test Suite
-      run: tox -vv -s false -- -n auto --run-network_bound
-      env:
-        PLATFORM: ${{ matrix.platform }}
+    # - name: Run Test Suite
+    #   run: tox --sitepackages -vv -s false -- -n auto --run-network_bound
+    #   env:
+    #     PLATFORM: ${{ matrix.platform }}
 
-    - name: Check for compliance with Python Best Practices
-      run: |
-        DIST_DIR=dist
-        echo "DIST_DIR=dist" >> $GITHUB_ENV
-        ls -l ./
-        mkdir ${DIST_DIR}
-        mv ".tox/${DIST_DIR}/cookiecutter_python-${PKG_VERSION}.tar.gz" "${DIST_DIR}"
-        mv ".tox/${DIST_DIR}/cookiecutter_python-${PKG_VERSION}-py3-none-any.whl" "${DIST_DIR}"
-        tox -e check -vv -s false
+    # - name: Check for compliance with Python Best Practices
+    #   run: |
+    #     DIST_DIR=dist
+    #     echo "DIST_DIR=dist" >> $GITHUB_ENV
+    #     ls -l ./
+    #     mkdir ${DIST_DIR}
+    #     mv ".tox/${DIST_DIR}/cookiecutter_python-${PKG_VERSION}.tar.gz" "${DIST_DIR}"
+    #     mv ".tox/${DIST_DIR}/cookiecutter_python-${PKG_VERSION}-py3-none-any.whl" "${DIST_DIR}"
+    #     tox -e check -vv -s false
 
-    - name: Aggregate Test Coverage Data
-      run: tox -e coverage --sitepackages -vv -s false
+    # - name: Aggregate Test Coverage Data
+    #   run: tox -e coverage --sitepackages -vv -s false
 
-    - name: Send Coverage Data to Codecov
-      uses: codecov/codecov-action@v2
-      with:
-        directory: ./.tox
-        env_vars: OS,PYTHON
-        fail_ci_if_error: true
-        files: ./.tox/coverage.xml
-        flags: unittests
-        name: codecov-umbrella
-        verbose: true
+    # - name: Send Coverage Data to Codecov
+    #   uses: codecov/codecov-action@v2
+    #   with:
+    #     directory: ./.tox
+    #     env_vars: OS,PYTHON
+    #     fail_ci_if_error: true
+    #     files: ./.tox/coverage.xml
+    #     flags: unittests
+    #     name: codecov-umbrella
+    #     verbose: true
 
-    - name: Upload Source & Wheel distributions as Artefacts
-      uses: actions/upload-artifact@v2
-      with:
-        # name: dist-${{ env.OS }}-${{ env.PYTHON }}  # TODO enable this
-        name: dist-${{ matrix.platform }}-${{ matrix.python-version }}
-        path: ${{ env.DIST_DIR }}
-        if-no-files-found: error
+    # - name: Run Documentation Tests
+    #   run: |
+    #     if ! [[ ${{ env.GG }} ]]
+    #       then
+    #         echo "Failed to read GG var, exported in previous step!"
+    #         echo "Exiting .."
+    #         exit 1
+    #       else
+    #         echo "Able to read the GG var exported from the previous step :)"
+    #       fi
+    #     tox -e docs -vv -s false
 
-    - name: Upload Coverage Data as Artefacts
-      uses: actions/upload-artifact@v2
-      with:
-        name: coverage-xml-data
-        path: ./.tox/coverage.xml
-        if-no-files-found: error
+    # - name: Upload Source & Wheel distributions as Artefacts
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     # name: dist-${{ env.OS }}-${{ env.PYTHON }}  # TODO enable this
+    #     name: dist-${{ matrix.platform }}-${{ matrix.python-version }}
+    #     path: ${{ env.DIST_DIR }}
+    #     if-no-files-found: error
+
+    # - name: Upload Coverage Data as Artefacts
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: coverage-xml-data
+    #     path: ./.tox/coverage.xml
+    #     if-no-files-found: error
 
     # - name: Download Coverage Data
     #   uses: actions/download-artifact@v2
